spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/consulta_facil?serverTimezone=America/Sao_Paulo&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
app.seed-demo=${SEED_DEMO:false}
